### ISSUE TITLE
[bug] Benchmark `benchmark_float_qps` fails if the index files were already available

### ISSUE THREAD

**Issue by alexanderguzhva** [zilliztech/knowhere#107]
Basically, whenever one runs `benchmark_float_qps` without any pre-generated index files then the benchmark will create indices and save ones into files, say, this happens for the very first run. But for the second one, when index files are already available, the benchmark fails with 'segmentation fault' error after `sift-128-euclidean | IVF_FLAT | nlist=1024, nprobe=10, k=100, R@=0.8000` and `sift-128-euclidean | IVF_FLAT | nlist=1024, nprobe=30, k=100, R@=0.9500` tests.

Steps to reproduce:
1. compile `knowhere` with `-o with_benchmark=True` option and in Release mode using a default compiler
2. download sift data file and put it in build/Release/benchmark, where the binary `benchmark_float_qps` is located
3. run `benchmark_float_qps` once, see it runs successfully and generates index files
4. run it for the second file and see `Segmentation fault` error

OS: ubuntu 20.04 / 22.04, x64 machine

**Comment by liliu-z** [comment]
Anyone on this?

**Comment by alexanderguzhva** [comment]
no longer an issue, it was fixed
