### ISSUE TITLE
`scripts/install_deps.sh` needs to be improved

### ISSUE THREAD

**Issue by alexanderguzhva** [zilliztech/knowhere#117]
The script does not work properly if knowhere is run inside a fresh plain linux docker container.
For ubuntu, the following packages are needed: `lsb-release`, `wget`, `sudo` and `git`.
It would be nice if `scripts/install_deps.sh` would install ones automatically.

**Comment by liliu-z** [comment]
How about the idea of dev container? I heard some of this requirements.

**Comment by liliu-z** [comment]
Looks like we can work with Knowhere by simply following `README`, this script seems useless. We need:
1. Check if any where use it.
2. Only keep pkg installation and put the instruction in `README`. All compilation work need to be removed.
3. We can try to make a pre-build .conan in the UT image for fast building. 

/assign @cydrain

**Comment by liliu-z** [comment]
Do we need to keep the `script/install_deps.sh`. Can you help delete it not? @cydrain
