### ISSUE TITLE
[FYI] building knowhere on MacOS with M2 cpu

### ISSUE THREAD

**Issue by alexanderguzhva** [zilliztech/knowhere#131]
1. clone repo
2. run `brew install llvm@16`
3. create `~/.conan/profiles/default` with the following data
```
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=clang
compiler.version=16
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CC=/opt/homebrew/Cellar/llvm@16/16.0.6/bin/clang
CXX=/opt/homebrew/Cellar/llvm@16/16.0.6/bin/clang++
```
4. run `mkdir build && cd build`
5. run `conan install .. --build=missing -o with_ut=True -s compiler.libcxx=libc++ -s build_type=Release`
6. conan won't build boost, the following libraries need to be disabled in `./conan/data/boost/1.83.0/_/_/export/conanfile.py` by adding the following lines around line 290:
```
self.options.without_fiber=True
self.options.without_json=True
self.options.without_nowide=True
self.options.without_url=True
self.options.without_wave=True
self.options.without_locale=True
self.options.without_math=True
self.options.without_graph=True
```
7. repeat step 5
8. comment out / remove `atomic` library usage in `CMakeLists.txt` files (`tests/ut/CMakeLists.txt` and `benchmark/CMakeLists.txt`). Somewhy MacOS do not need ones, unlike, say, Ubuntu
9. run 'conan build ..`
10. run generated unit test `build/Release/tests/ut/knowhere_tests`, where will be a failed test (`Knowhere SIMD config`)

apple's clang 14 won't work
brew's clang 14 won't work

**Comment by liliu-z** [comment]
keep it open
