### ISSUE TITLE
[BUG] IVF `GetVectorByIds` interface has concurrence problem

### ISSUE THREAD

**Issue by foxspy** [zilliztech/knowhere#132]
IVF index constructs the id->offset map during getvectors stage :  https://github.com/zilliztech/knowhere/blob/main/src/index/ivf/ivf.cc#L580. This design will cause write/write concurrence when user calls the interface concurrently because the idmap is shared and not thread-safe.

related milvus issue: #https://github.com/milvus-io/milvus/issues/27390

**Comment by liliu-z** [comment]
@elstic Fixed

**Comment by elstic** [comment]
> @elstic Fixed

Yes, it was fixed.
I'm not getting search failures on the milvus side of the continuous concurrency test
