### ISSUE TITLE
Filtering documentation and code pointer

### ISSUE THREAD

**Issue by patelprateek** [zilliztech/knowhere#172]
Hi , thanks for this amazing work , seems like exactly what i have been looking to use.
I observer there are multiple ANN algorithms integrated already. i am curios do we enable filtered search as well i.e topk vectors within some additional filtering criteria (country=xyz and some_threshold > 0.3) 

If you can provide me any pointers and benchmarks i can try to run on my internal dataset that would be great.
really appreciate the work here

**Comment by liliu-z** [comment]
https://github.com/zilliztech/VectorDBBench Can help test Milvus E2E, with 1% and 99% filtering rate cases inside. And you can add your own cases to test more.
