### ISSUE TITLE
knowhere vs milvus

### ISSUE THREAD

**Issue by patelprateek** [zilliztech/knowhere#173]
i read the readme stating use  knowhere within milvus , what exactly is the difference between this repo and the knowhere within milvus , does milvus provide some more functionality or perf on top of knowhere . 
When should one typically depend directly on this repo rather than milvus ?

**Comment by jiaoew1991** [comment]
> i read the readme stating use knowhere within milvus , what exactly is the difference between this repo and the knowhere within milvus , does milvus provide some more functionality or perf on top of knowhere . When should one typically depend directly on this repo rather than milvus ?

In fact, Knowhere is the core of Milvus. Knowhere is a library while Milvus is a database, just like the relationship between InnoDB and MySQL.

**Comment by patelprateek** [comment]
@jiaoew1991 : thanks for clarifying this. 
Is there some documentation i can look at to understand different index type supported 
Also do we support filtering ?

**Comment by jiaoew1991** [comment]
> @jiaoew1991 : thanks for clarifying this. Is there some documentation i can look at to understand different index type supported Also do we support filtering ?

You can get it from here https://milvus.io/docs/index.md

**Comment by patelprateek** [comment]
@jiaoew1991 :  do we support filtering for hnsw ?

I have 2 use cases  : 
- get topk similar documents where attribute=XYZ (some categorical attribute)
- get topk similar documents where threshold > 0.xyz (some float value ) 

Do we create some seperate metdata index for this ? when reading the code i do see bitsetview , curios to learn how we create bitsets (from some other index ?)

**Comment by liliu-z** [comment]
> @jiaoew1991 : do we support filtering for hnsw ?
> 
> I have 2 use cases :
> 
> * get topk similar documents where attribute=XYZ (some categorical attribute)
> * get topk similar documents where threshold > 0.xyz (some float value )
> 
> Do we create some seperate metdata index for this ? when reading the code i do see bitsetview , curios to learn how we create bitsets (from some other index ?)

You can create a scalar index based on your case, but no index by default. The relative code is inside Milvus. Knowhere is only responsible for vector search
