### ISSUE TITLE
Filtering support for hybrid search

### ISSUE THREAD

**Issue by patelprateek** [zilliztech/knowhere#178]
I was reading through some of the code (hnswlib) and observed that we support bitsets to do some filtering while traversing the graph.
I would like to learn more about how to create those bitsets , are they generated through some other metadata index 

my use case is when building ann index i have some additional metadata (2 types)
1) categorical for ex: color=red , enabled_lanuage=[english, french] 
2) float, numeric ex : some_threshold_score > 0.35 

Is there some alternative index wwe build on these metadata to create bitsets, any pointers on how to do this is appreciated

**Comment by liliu-z** [comment]
> I was reading through some of the code (hnswlib) and observed that we support bitsets to do some filtering while traversing the graph. I would like to learn more about how to create those bitsets , are they generated through some other metadata index
> 
> my use case is when building ann index i have some additional metadata (2 types)
> 
> 1. categorical for ex: color=red , enabled_lanuage=[english, french]
> 2. float, numeric ex : some_threshold_score > 0.35
> 
> Is there some alternative index wwe build on these metadata to create bitsets, any pointers on how to do this is appreciated

Bitset generation is inside Milvus' code. It now support some basic indexes type like binary search, trie tree, etc.

**Comment by PwzXxm** [comment]
> I was reading through some of the code (hnswlib) and observed that we support bitsets to do some filtering while traversing the graph. I would like to learn more about how to create those bitsets , are they generated through some other metadata index
> 
> my use case is when building ann index i have some additional metadata (2 types)
> 
> 1. categorical for ex: color=red , enabled_lanuage=[english, french]
> 2. float, numeric ex : some_threshold_score > 0.35
> 
> Is there some alternative index wwe build on these metadata to create bitsets, any pointers on how to do this is appreciated

Hi there, the dimension of the bitset is the same as the number of vectors you used to build the ANN index. So each bit corresponds to a vector, indicating whether it is deleted or filtered out. To generate the bitset, you may take a look at https://github.com/zilliztech/knowhere/blob/f7fd047d88ba7207fb172e2a649c84ccc99ac99c/python/knowhere/knowhere.i#L228

If you want a wider range of support, such as adding scalars along with the vectors, rather than implementing by yourself, Milvus takes care of all these. https://github.com/milvus-io/milvus. Or you can checkout Zilliz Cloud https://zilliz.com/.

**Comment by patelprateek** [comment]
@PwzXxm : would this approach work for streaming indexing scenario , it seems to me bitset size needs to be consistent with all elements in ann index which in streaming scenario can keep changing

**Comment by PwzXxm** [comment]
> @PwzXxm : would this approach work for streaming indexing scenario , it seems to me bitset size needs to be consistent with all elements in ann index which in streaming scenario can keep changing

Yes, Milvus has the concepts of growing segments and sealed segments, and it also depends on your consistency levels https://milvus.io/docs/consistency.md. All these are handled in the upper-level Milvus as they related to the distributed system. In Knowhere, we only offer capability as a library focusing on ANNS.

**Comment by patelprateek** [comment]
@PwzXxm : the segments are only for inverted index or ann as well. If we follow a lucene/elastic style approach of building new segments for inverted index , we also need to ensure the ann index also contain same elements , do we put all inverted index segment and ann index for the documents in those segments on same physical node/machine ?

**Comment by PwzXxm** [comment]
> @PwzXxm : the segments are only for inverted index or ann as well. If we follow a lucene/elastic style approach of building new segments for inverted index , we also need to ensure the ann index also contain same elements , do we put all inverted index segment and ann index for the documents in those segments on same physical node/machine ?

Take this example
```
data=[
    {"id": 0, "vector": [0.3580376395471989, -0.6023495712049978, 0.18414012509913835, -0.26286205330961354, 0.9029438446296592], "color": "pink_8682"},
    {"id": 1, "vector": [0.19886812562848388, 0.06023560599112088, 0.6976963061752597, 0.2614474506242501, 0.838729485096104], "color": "red_7025"},
    {"id": 2, "vector": [0.43742130801983836, -0.5597502546264526, 0.6457887650909682, 0.7894058910881185, 0.20785793220625592], "color": "orange_6781"},
    {"id": 3, "vector": [0.3172005263489739, 0.9719044792798428, -0.36981146090600725, -0.4860894583077995, 0.95791889146345], "color": "pink_9298"},
    {"id": 4, "vector": [0.4452349528804562, -0.8757026943054742, 0.8220779437047674, 0.46406290649483184, 0.30337481143159106], "color": "red_4794"},
    {"id": 5, "vector": [0.985825131989184, -0.8144651566660419, 0.6299267002202009, 0.1206906911183383, -0.1446277761879955], "color": "yellow_4222"},
    {"id": 6, "vector": [0.8371977790571115, -0.015764369584852833, -0.31062937026679327, -0.562666951622192, -0.8984947637863987], "color": "red_9392"},
    {"id": 7, "vector": [-0.33445148015177995, -0.2567135004164067, 0.8987539745369246, 0.9402995886420709, 0.5378064918413052], "color": "grey_8510"},
    {"id": 8, "vector": [0.39524717779832685, 0.4000257286739164, -0.5890507376891594, -0.8650502298996872, -0.6140360785406336], "color": "white_9381"},
    {"id": 9, "vector": [0.5718280481994695, 0.24070317428066512, -0.3737913482606834, -0.06726932177492717, -0.6980531615588608], "color": "purple_4976"}
]

res = client.insert(
    collection_name="quick_setup",
    data=data
)
```
Let's say that these inserted data is in the same segment. The indices are based on columns, say, ANN index on the column of `vector` and inverted index on the column of `color`. They are on the same physical node/machine.
