### ISSUE TITLE
After upgrade to faiss-1.7.4, Milvus ut-cpp coredump

### ISSUE THREAD

**Issue by cydrain** [zilliztech/knowhere#192]
https://github.com/milvus-io/milvus/pull/28325
https://github.com/milvus-io/milvus/pull/28356
https://github.com/milvus-io/milvus/pull/28402

Above 3 PRs report same ut-cpp coredump

**Comment by alexanderguzhva** [comment]
@cydrain I cannot reproduce it locally either, even with valgrind, just like you. I'll try fully replicating `builder.sh` from milvus

**Comment by cydrain** [comment]
use following steps, but cannot reproduce this coredump:

under Milvus root dir, run "make build-cpp-with-unittest"
run ./cmake_build/bin/all_tests --gtest_filter="*BinaryVecIndex*"
 ~/vec/milvus/ [master*] ./cmake_build/bin/all_tests --gtest_filter="*BinaryVecIndex*"
Note: Google Test filter = *BinaryVecIndex*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BinaryVecIndex
[ RUN      ] BinaryVecIndex.All
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231114 15:16:27.458635 3248961 factory.cc:20] [KNOWHERE][Create][all_tests] create knowhere index BIN_IVF_FLAT with version 1
W20231114 15:16:27.458894 3248961 thread_pool.h:153] [KNOWHERE][GetGlobalSearchThreadPool][all_tests] Global Search ThreadPool has not been initialized yet, init it with threads num: 12
W20231114 15:16:27.459206 3248961 ivf.cc:209] [KNOWHERE][MatchNlist][all_tests] nlist(16) is too large, adjust to a proper value
W20231114 15:16:27.459316 3248961 ivf.cc:211] [KNOWHERE][MatchNlist][all_tests] Row num 10 match nlist 1
WARNING clustering 10 points to 1 centroids: please provide at least 39 training points
I20231114 15:16:27.519685 3248961 time_recorder.cc:49] [KNOWHERE][PrintTimeRecord][all_tests] Build index: done (60.495163 ms)
I20231114 15:16:27.519801 3248961 factory.cc:20] [KNOWHERE][Create][all_tests] create knowhere index BIN_IVF_FLAT with version 1
[       OK ] BinaryVecIndex.All (63 ms)
[----------] 1 test from BinaryVecIndex (63 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (63 ms total)
[  PASSED  ] 1 test.

**Comment by alexanderguzhva** [comment]
https://github.com/milvus-io/milvus/actions/runs/6892564731/job/18750145333?pr=28473 passed
