### ISSUE TITLE
[bug] SetIds in python raise 'TypeError' Exception

### ISSUE THREAD

**Issue by JohnsonLee-debug** [zilliztech/knowhere#285]
The following code
```python
def test_setids():
    path = '../../../dataset/sift1m/sift/sift_base.fvecs'
    data = fvec_read(path, 0, 1000)
    ids = np.arange(0, 1000, dtype=np.int64)
    ds = kw.ArrayToDataSet(data)
    ds.SetIds(ids.ctypes.data)
```
raise an 'TypeError'
```
Traceback (most recent call last):
  File "/home/envd/knowhere_testing/src/knowhere_test/simulator/Client.py", line 55, in <module>
    test_setids()
  File "/home/envd/knowhere_testing/src/knowhere_test/simulator/Client.py", line 51, in test_setids
    ds.SetIds(ids.ctypes.data)
  File "/home/envd/.local/lib/python3.10/site-packages/knowhere/swigknowhere.py", line 186, in SetIds
    return _swigknowhere.DataSet_SetIds(self, ids)
TypeError: in method 'DataSet_SetIds', argument 2 of type 'int64_t const *'
```

But I think the code should be able to call 'DataSet.SetIds' method.

**Comment by cydrain** [comment]
Hi @JohnsonLee-debug ,
"SetIds()" need the param with type "int64_t const *", but "ids.ctypes.data" is with type "int".
```
>>> print(type(ids.ctypes.data))
PyDev console: starting.
<class 'int'>
```

This interface "SetIds()" is used inside knowhere, there is no need to call it in pyknowhere.

**Comment by JohnsonLee-debug** [comment]
I'm doing some test with knowhere. So is there anyway to set id in pyknowhere?

**Comment by cydrain** [comment]
> I'm doing some test with knowhere. So is there anyway to set id in pyknowhere?

hi @JohnsonLee-debug , the ids in knowhere are auto-generated, it does not support to set an outside id
