### ISSUE TITLE
Reconcile differences in device dataset ownership for IVF Flat once supported by RAFT

### ISSUE THREAD

**Issue by wphicks** [zilliztech/knowhere#333]
After RAFT resolves https://github.com/rapidsai/raft/issues/2082, the special handling for IVF Flat dataset ownership [here](https://github.com/zilliztech/knowhere/pull/330/files#diff-74b0fc3b89845b44f6e81c1655a196fecc400bd6399aef084cabced97562c88eR396-R406) can be removed.

**Comment by Presburger** [comment]
keep trace
