### ISSUE TITLE
Remove special handling for IVF PQ training on host datasets once supported by RAFT

### ISSUE THREAD

**Issue by wphicks** [zilliztech/knowhere#335]
Once https://github.com/rapidsai/raft/issues/2083 is resolved, remove [special handling](https://github.com/zilliztech/knowhere/pull/330/files#diff-cbb9e3a9a0c7e793757f6deac180be4a5d6bd0541494dfbcebe91b7af5ed423eR201-R202) for training RAFT IVF PQ from a host dataset.

**Comment by Presburger** [comment]
keep trace
