### ISSUE TITLE
Allow training IVF Flat on host data once supported by RAFT 

### ISSUE THREAD

**Issue by wphicks** [zilliztech/knowhere#336]
After resolution of https://github.com/rapidsai/raft/issues/1178, enable training of IVF flat from host data [here](https://github.com/zilliztech/knowhere/pull/330/files#diff-cbb9e3a9a0c7e793757f6deac180be4a5d6bd0541494dfbcebe91b7af5ed423eR204).

**Comment by Presburger** [comment]
keep trace
