### ISSUE TITLE
Range Seach with IVF Index Behaving Strangely

### ISSUE THREAD

**Issue by hakan458** [zilliztech/knowhere#345]
When using range search on a collection with 100k records, using IVF_SQ8 index, I am seeing some strange behavior which does not make sense to me. I will separate the different behaviors below. They are probably related but just to be clear about what I am seeing. 

1. If I perform a vector search without range params (radius and range_filter) , then perform the same exact search (ref embedding, filters, etc) but using `radius = 10` , I get completely different results. 

2. If I perform a vector search using `radius = 10` and `limit = 16384` and take the distance of the 16384th record, and use that as the `radius` for my following search, I get zero results back. When performing the initial search with `radius = 10` , I see that every single record has a distance of < 1.608 . If I use 1.608 as the radius, I get zero results which is very unexpected. I would expect to get the same 16384 results in this case. 

3. Using the above example, if I use `radius = 2` , I get the same 16384 results that I did when using `radius = 10`. If I use `radius = 1.7` , I get around 10k records back. I would still expect to get 16384 in this case. 

How is this possible? Does range search work in a way I dont understand? Previously we were using DiskANN for our collections, and that worked very well with range search, but was extremely slow. E.g. if I searched without any radius, and the first 10 results were < 1.0 distance and the 11th result was 1.1 distance - if I used 1.0 as the radius I would get those 10 results that I saw initially. 

Is there way to get IVF_SQ8 collections to behave with range search like collections with DiskANN index do? 

If this is not a bug and intended behavior one way or another, I think I will resort to always getting the max topk (16384) and performing the range filtering myself.

**Comment by hakan458** [comment]
Any comments on this?

**Comment by alexanderguzhva** [comment]
@hakan458 Do you have a simple python script to reproduce this behavior by chance? Thanks

**Comment by hakan458** [comment]
I can provide one but it depends on my existing collection, would that help still? I dont have a simple script to create a collection and repro this behavior

**Comment by alexanderguzhva** [comment]
Well, any script works, unless it is complicated for you to provide it :) I have a suggestion of where the problem is (inside our code) and I'd like to make sure that we solve the correct problem.

**Comment by hakan458** [comment]
Sure I will just provide you an example, using my collection, of how I reproduce this problem

```
from pymilvus import Collection, connections, utility

connections.connect(
    alias="default",
    host="127.0.0.1",
    user='root',
    password='Milvus',
)

c = Collection("Df7d753fd_3dd8_4c91_b42c_dd3ed0a5e194")

search_params_threshold = {'params': {'nprobe': 16, 'radius': 10.0}, 'metric_type': 'L2'}

upper_limit_results = c.search(
    data=[reference_embedding],
    anns_field='img',
    expr=None,
    param=search_params_threshold,
    limit=1,
    offset=16384,
    output_fields=['candidate_task_id', 'storage_id'],
    consistency_level='Strong'
)[0]

# upper_limit_results value
# ["id: 446905980345079841, distance: 1.6078476905822754, entity: ...."]

search_params_max_distance = {'params': {'nprobe': 16, 'radius':  1.6}, 'metric_type': 'L2'} # note using distance from previous result

results_using_distance = c.search(
    data=[reference_embedding],
    anns_field='img',
    expr=None,
    param=search_params_max_distance,
    limit=16384,
    offset=0,
    output_fields=['candidate_task_id', 'storage_id'],
    consistency_level='Strong'
)[0]

# results_using_distance value 
# [] 
```

**Comment by hakan458** [comment]
For item number 1, I got an explanation on the Milvus discord channel, which makes sense, Can you confirm this behavior? Seems to be related to number 3 as well 

```
The algorithm of normal search and range search for IVF index is different:

Normal search:

    calculate the distance between the target vector and the central vectors of the nlist buckets, find out the nearest nprobe buckets
    calculate the distance between the target vector and all the vectors in the nproble buckets, find out the topk result



Range search:

    calculate the distance between the target vector and the central vectors of the nlist buckets, and arrange the distances in ascending order
    calculate the distance between the target vector and vectors in the nearest bucket, find out all the items whose distance is less than the radius
    calculate the distance between the target vector and vectors in the No.2 nearest bucket, find out all the items whose distance is less than the radius
    do the same thing to the No.3 nearest bucket util All the bucket are calculated
    arrange all the distances in ascending order, and pick up the topk result


So, we can see, Normal search only searches the nprobe buckets, Range search ignores the "nprobe" parameter and searches all the nlist buckets. 
The search scope is different then the results are different.
Normal search in "nprobe" buckets is "find some near buckets and search in the buckets", with fewer buckets searched, the performance is good, the major purpose is to improve performance.
Range search is "search all the buckets to find out items whose distance is less than radius", the purpose is to find out all the items in range, not for performance.
If you set the nprobe=nlist, and set a large radius, you will see the same results.
```
https://discord.com/channels/1160323594396635310/1194773654576308344

**Comment by alexanderguzhva** [comment]
Yes, I think I see this behavior in the code.
