### ISSUE TITLE
python bindings and example

### ISSUE THREAD

**Issue by patelprateek** [zilliztech/knowhere#361]
I am moving some of my production workload to use zilliz knowhere core ann engines . Are there any example python notebook or code that i can try to evaluate how it performs on some of our internal datasets to ensure no quality regressions when migrating from legacy ann engine ? Any pointers or example code api would help . 
Do you guys also support java bindings ? any tooling to compare different indexing algorithms (build , query times , memory footprints).

**Comment by liliu-z** [comment]
We have pyknowhere which is wrapper upon Knowhere using swig https://github.com/zilliztech/knowhere?tab=readme-ov-file#gen-python-wheelneed-realse-build . 
This is more test purpose, so the stability cannot be guaranteed.

And we don't have a plan to support other bindings.
