### ISSUE TITLE
optimizations for graph based algorithms

### ISSUE THREAD

**Issue by patelprateek** [zilliztech/knowhere#362]
In the benchmark section for https://github.com/zilliztech/pyglass , i see pyglass performaing better than knowhere graph based algorithms ? Are there plans to port those optimizations to this code base ? 
trying to understand what pyglass does different and if that code base in maintained ?

**Comment by liliu-z** [comment]
pyglass is an experimental product of our close-sourced index solution. Doesn't like our close sourced solution aiming for performance. Knowhere is an open-sourced ANNS adaptor, its goal is to adapt open-sourced 3rd party algorithm.

Also, some optimization on pyglass is benchmark orientated, but Knowhere is a production level lib. So we will not apply these strategies.
