### ISSUE TITLE
What is the max dimension for binary vectors? 

### ISSUE THREAD

**Issue by xiaofan-luan** [zilliztech/knowhere#363]
Currently the milvus limitation is 32768 for binary vector, but I believe this is for float vector?

https://github.com/milvus-io/milvus/issues/30285

What should be the right limitation?

**Comment by cydrain** [comment]
@xiaofan-luan 
knowhere has no dimension limitation for both float and binary vector

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan knowhere has no dimension limitation for both float and binary vector

Then please check and fix on Milvus side?

**Comment by xiaofan-luan** [comment]
close it for now.
it is 32768 * 8
