### ISSUE TITLE
error: ‘gettid’ was not declared in this scope

### ISSUE THREAD

**Issue by Ghostbaby** [zilliztech/knowhere#401]
Centos 8 ARM build milvus got errors：
`[ 50%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/brute_force.cc.o
[ 50%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/knowhere_config.cc.o
In file included from /root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/common/comp/brute_force.cc:21:
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:38:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:38:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
[ 51%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/index_node_thread_pool_wrapper.cc.o
In file included from /root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/common/comp/knowhere_config.cc:21:
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:38:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:38:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
[ 52%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/prometheus_client.cc.o
[ 52%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/range_util.cc.o
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:76: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/brute_force.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:90: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/knowhere_config.cc.o] Error 1
[ 53%] Linking CXX static library ../../lib/libmilvus_proto.a
make[3]: Leaving directory '/root/milvus/cmake_build'
[ 53%] Built target milvus_proto
In file included from /root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/src/common/index_node_thread_pool_wrapper.cc:14:
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:38:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:38:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:160: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/index_node_thread_pool_wrapper.cc.o] Error 1
make[3]: Leaving directory '/root/milvus/cmake_build'
make[2]: *** [CMakeFiles/Makefile2:1277: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/all] Error 2
make[2]: Leaving directory '/root/milvus/cmake_build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/root/milvus/cmake_build'
make: *** [Makefile:216: build-cpp] Error 1`

**Comment by bydeath** [comment]
I got the same error on x86_64 centos8, milvus version is 2.3.12.
[ 52%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/brute_force.cc.o
[ 52%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/knowhere_config.cc.o
In file included from /root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/src/common/comp/knowhere_config.cc:21:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
In file included from /root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/src/common/comp/brute_force.cc:21:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:90: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/knowhere_config.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:76: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/brute_force.cc.o] Error 1
make[3]: Leaving directory '/root/milvus-2.3.12/cmake_build'
make[2]: *** [CMakeFiles/Makefile2:1423: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/all] Error 2
make[2]: Leaving directory '/root/milvus-2.3.12/cmake_build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/root/milvus-2.3.12/cmake_build'
make: *** [Makefile:218: build-cpp] Error 1
[root@VM-12-4-centos milvus-2.3.12]#  ^C
[root@VM-12-4-centos milvus-2.3.12]# tail -30 make_milvus-15.log 
make[3]: Entering directory '/root/milvus-2.3.12/cmake_build'
[ 52%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/brute_force.cc.o
[ 52%] Building CXX object thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/knowhere_config.cc.o
In file included from /root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/src/common/comp/knowhere_config.cc:21:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
In file included from /root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/src/common/comp/brute_force.cc:21:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h: In lambda function:
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: error: ‘gettid’ was not declared in this scope
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
/root/milvus-2.3.12/cmake_build/thirdparty/knowhere/knowhere-src/include/knowhere/comp/thread_pool.h:42:47: note: suggested alternative: ‘getgid’
                 if (setpriority(PRIO_PROCESS, gettid(), 19) != 0) {
                                               ^~~~~~
                                               getgid
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:90: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/knowhere_config.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/build.make:76: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/src/common/comp/brute_force.cc.o] Error 1
make[3]: Leaving directory '/root/milvus-2.3.12/cmake_build'
make[2]: *** [CMakeFiles/Makefile2:1423: thirdparty/knowhere/knowhere-build/CMakeFiles/knowhere.dir/all] Error 2
make[2]: Leaving directory '/root/milvus-2.3.12/cmake_build'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/root/milvus-2.3.12/cmake_build'
make: *** [Makefile:218: build-cpp] Error 1
