### ISSUE TITLE
[bug] CFG_LIST, add list parameter, crashed

### ISSUE THREAD

**Issue by autoxj** [zilliztech/knowhere#46]
I tried to add a list parameter, but the program crashed when it reached this code line:
https://github.com/zilliztech/knowhere/blob/3d21950cc27e8383c9435dd2c011b7635fd44ac3/include/knowhere/config.h#L437C52-L437C52

`ptr->val`may not has value. This is how I modified, while I don't quite understand.
```
*ptr->val = CFG_LIST();
*ptr->val = ptr->default_val;
for (auto&& i : json[it.first]) {
    ptr->val->value().push_back(i);
}
```

**Comment by liliu-z** [comment]
@autoxj 
Yes this a a bug, we will fix is in the next release.

You can keep the original code and replace `CFG_LIST` with `std::make_optional<std::list<int>>()` to solve it.

**Comment by Presburger** [comment]
good catch
