### ISSUE TITLE
 Where can I get the "./devcontainer.sh" mentioned in .devcontainer.json?  

### ISSUE THREAD

**Issue by cheetahsec** [zilliztech/knowhere#47]
Where can I get the "./devcontainer.sh"and "docker-compose-devcontainer.yml" mentioned in .devcontainer.json?  

```
{
    "name": "Milvus Distributed Dev Container Definition",
    "dockerComposeFile": [
        "./docker-compose-devcontainer.yml"
    ],
    "service": "builder",
    "initializeCommand": "./devcontainer.sh",
    "workspaceFolder": "/go/src/github.com/milvus-io/knowhere",
    "remoteEnv": {
        "GOPROXY": "https:goproxy.cn"
    },
    "extensions": [
        "ms-vscode.cpptools",
        "golang.go"
    ]
}
```

**Comment by liliu-z** [comment]
Aha, Looks this is some legacy thing, will remove it from our codebase.

**Comment by cheetahsec** [comment]
> Aha, Looks this is some legacy thing, will remove it from our codebase.

 Why remove it, can't dev containers be provided like the milvus project? it's very friendly for those who want to get started quickly with development and debugging

**Comment by liliu-z** [comment]
> > Aha, Looks this is some legacy thing, will remove it from our codebase.
> 
> Why remove it, can't dev containers be provided like the milvus project? it's very friendly for those who want to get started quickly with development and debugging

This is a good call. I think Knowhere doesn't have it from day 1. This is copied from Milvus repo when we try to split Milvus and Knowhere.
We will evaluate add the dev containers back as your suggestion. Thanks!
