### ISSUE TITLE
ASAN-compiled knowhere library got missing symbols

### ISSUE THREAD

**Issue by alexanderguzhva** [zilliztech/knowhere#531]
Fails for both gcc and clang.
I suspect that linker flags are not set properly.

The simplest way is to test it with vector db bench.

for gcc: currently, it can be fixed by adding the output of `gcc -print-file-name=libasan.so` into `LD_PRELOAD`

**Comment by liliu-z** [comment]
@alexanderguzhva is this still a problem?
