### ISSUE TITLE
pip3 install pyknowhere.xx.whl, but "import pyknowhere" Error: ModuleNotFoundError: No module named 'pyknowhere'

### ISSUE THREAD

**Issue by zjx1230** [zilliztech/knowhere#545]
Hello, Everyone! I want to use the package pyknowhere. I followed github's [guide](https://github.com/zilliztech/knowhere) and successfully compiled the package, and after the installation was successful, it still prompted that the python package could not be found, what is going on? 
**The installed package only has the directory pyknowhere-0.0.0.dist-info and no directory pyknowhere**
Here are the details:

> (z00xxxxxxx) [root@node57 python]# pip3 install ./dist/pyknowhere-0.0.0-cp310-cp310-linux_x86_64.whl 
> Looking in indexes: http://mirrors.tools.huawei.com/pypi/simple
> Processing ./dist/pyknowhere-0.0.0-cp310-cp310-linux_x86_64.whl
> Installing collected packages: pyknowhere
> Successfully installed pyknowhere-0.0.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> (z00xxxxxxx) [root@node57 python]# python
> Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> import pyknowhere
> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'pyknowhere'
> exit()
> 
> (z00xxxxxxx) [root@node57 python]# ls /root/miniconda3/envs/z00878108/lib
> /python3.10/site-packages/ | grep knowhere*
> knowhere
> knowhere-1.0.0.dist-info
> pyknowhere-0.0.0.dist-info

**OS**: CentOS 7

**Comment by SimFG** [comment]
It seems that you should use `import knowhere`
![image](https://github.com/zilliztech/knowhere/assets/21985684/d8f2bdae-4bfc-4fe8-a446-6d6c297d8c00)

**Comment by zjx1230** [comment]
> It seems that you should use `import knowhere` ![image](https://private-user-images.githubusercontent.com/21985684/328179944-d8f2bdae-4bfc-4fe8-a446-6d6c297d8c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTk4NjcsIm5iZiI6MTcxNDk5OTU2NywicGF0aCI6Ii8yMTk4NTY4NC8zMjgxNzk5NDQtZDhmMmJkYWUtNGJmYy00ZmU4LWE0NDYtNmQ2YzI5N2Q4YzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyNDYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NmNkZjA3YzQ0ZTdhOGFjNGJkODZmMWY0MjdiOTkzY2Y1OGUxMjJkYjM0Mzc5ZDYzMGU4OTE4YmNkODRhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LAkA04JygQC2wpqCPoOc6WTRXgR9VbFrWOWfPyi2-Io)

But, the project 'ann-benchmarks' has source code `pyknowhere.Index()`, `import knowhere` report error 'No Attribute'.

**Comment by zjx1230** [comment]
> This seems to be due to version inconsistency. I see that ['ann-benchmarks'](https://github.com/erikbern/ann-benchmarks) uses version 1.x, but now knowhere should be version 2.x ![image](https://private-user-images.githubusercontent.com/21985684/328191594-ee50cca6-0618-490e-be28-95adf6ac7ba9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTAwOTksIm5iZiI6MTcxNTAwOTc5OSwicGF0aCI6Ii8yMTk4NTY4NC8zMjgxOTE1OTQtZWU1MGNjYTYtMDYxOC00OTBlLWJlMjgtOTVhZGY2YWM3YmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDE1MzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMmFkODFlMWM3MWIwMDg3ZTUxYTQzNDg1Mjg3NGJjNzUyZDFkNmYzOTQ2N2YyZWNkODIyNzViZmM5YWM1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tq_rqa1XY9xCTMZDovRl_fuPXWBjB7t_Ws1g5XTPvwk)

However, when I checkout 1.x branch to generate the `pyknowhere` in the knowhere project, it still report error: `Not Found module`. Here is the details:

> (z00xxxxx) [root@node57 knowhere]# git branch -v
> \* 1.x c0aa5fb Fix DiskANN's Async cache making (#250)
>
> (z00xxxxx) [root@node57 knowhere]# cd python/
>
> (z00xxxxx) [root@node57 python]# pip3 install ./dist/knowhere-1.0.0-cp310-cp310-linux_x86_64.whl
> Looking in indexes: http://mirrors.tools.huawei.com/pypi/simple
> Processing ./dist/knowhere-1.0.0-cp310-cp310-linux_x86_64.whl
> Installing collected packages: knowhere
> Successfully installed knowhere-1.0.0
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
>
> (z00xxxxx) [root@node57 python]# python
>      Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
>      Type "help", "copyright", "credits" or "license" for more information.
>      import pyknowhere
>      Traceback (most recent call last):
>      File "<stdin>", line 1, in <module>
>      ModuleNotFoundError: No module named 'pyknowhere'

**Comment by zjx1230** [comment]
How to import pyknowhere? I can't use it.

**Comment by SimFG** [comment]
I think this project ['ann-benchmarks'](https://github.com/erikbern/ann-benchmarks) should use a historical version, but I am not sure. If you want to run it, I suggest you modify the relevant code in 'ann-benchmarks' according to the current knowhere code

**Comment by zjx1230** [comment]
> Hello, Everyone! I want to use the package pyknowhere. I followed github's [guide](https://github.com/zilliztech/knowhere) and successfully compiled the package, and after the installation was successful, it still prompted that the python package could not be found, what is going on? **The installed package only has the directory pyknowhere-0.0.0.dist-info and no directory pyknowhere** Here are the details:

Sorry, I can't do it. The work so hard. I think there must be a version of the source code that can generate this corresponding package, otherwise the [ann-benchmark](https://github.com/erikbern/ann-benchmarks) project cannot run the algorithm. If anyone knows please let me know, thank you very much!

**Comment by zjx1230** [comment]
> I think this project ['ann-benchmarks'](https://github.com/erikbern/ann-benchmarks) should use a historical version, but I am not sure. If you want to run it, I suggest you modify the relevant code in 'ann-benchmarks' according to the current knowhere code

Sorry, I can't do it. The work so hard. I think there must be a version of the source code that can generate this corresponding package, otherwise the [ann-benchmark](https://github.com/erikbern/ann-benchmarks) project cannot run the algorithm. If anyone knows please let me know, thank you very much!
