### ISSUE TITLE
Fix GetVectorById for Faiss_HNSW

### ISSUE THREAD

**Issue by liliu-z** [zilliztech/knowhere#778]
`GetVectorById` need to return an error code if there is no raw data available (If the data type is FP16, then the raw data need to be FP16).

So we need a raw data existence check there.

_Originally posted by @liliu-z in https://github.com/zilliztech/knowhere/pull/746#discussion_r1728652992_

**Comment by alexanderguzhva** [comment]
@alexanderguzhva Isn't it handled by `::HasRawData()` method?

**Comment by liliu-z** [comment]
> @alexanderguzhva Isn't it handled by `::HasRawData()` method?

Good question. Sorry the API definition isn't clear. The assumption is that `HasRawData` & `GetVectorById` are two individual function, meaning ppl are allow to call `GetVectorById` without calling `HasRawData` before. Although we hope users to call them in order, there are no hard limit to guarantee this.
