### ISSUE TITLE
[bug] possible flaky e2e test test_diskann_range_precision

### ISSUE THREAD

**Issue by zhengbuqian** [zilliztech/knowhere#78]
In e2e test run of #75 which didn't touch DiskANN code, TestKNN.test_diskann_range_precision[ssnpp] failed https://ci.milvus.io:18080/blue/organizations/jenkins/kn2/detail/PR-75/6/pipeline, likely due to it being flaky. E2E for #75 is being reran and will update once it finishes.

**Comment by liliu-z** [comment]
Any update?

**Comment by zhengbuqian** [comment]
it didn't happen again for quite some time, closing issue
