### ISSUE TITLE
Refactor knowhere UT

### ISSUE THREAD

**Issue by cydrain** [zilliztech/knowhere#809]
Target:
1. code coverage > 80%
2. runtime for each case < 5s

https://zilliverse.feishu.cn/wiki/S8JtwBcIyiPWYkkdhqdcJalmnM6
Task items:
- [x]  update test_config
- [x]  update test_knowhere_init
- [x]  update test_index_check
- [x]  update test_utils for thread_pool
- [ ]  update test_feder for diskann
- [x]  add ut for index.h / index_node.h / index_node_xxx.h
- [x]  add ut for src/common
- [x]  re-write test_simd
- [ ]  add test for cluster ( @chasingegg )
- [ ]  add test for bruteforce sparse ( @zhengbuqian )
- [ ]  add test for index range search ( @zhengbuqian )
- [ ]  add test for index iterator ( @zhengbuqian )
- [ ]  use trompeloeil to mock index ( @cydrain )

**Comment by liliu-z** [comment]
Let's first introduce some timeout mechanism
